name: Staging

on:
  push:
    branches: [ staging ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: node:14.15.4-slim
    steps:
      - uses: actions/checkout@v2

      - name: Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Cache NPM Dependencies
        id: node_modules
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: node_modules-${{ hashFiles('**/lockfiles') }}

      - name: Install NPM Dependencies
        if: steps.node_modules.outputs.cache-hit != 'true'
        run: npm i

      - name: Build Angular
        run: |
          npm install
          npm install -g @angular/cli
          npm update
          npm install typescript@4.4
          ls -l
          ng build --configuration=stg
          ls -l
          
      - name: Package Dependencies
        run: |
          cd dist && tar -pczf /tmp/dist.tar.gz .
          du -sh /tmp/dist.tar.gz

      - name: Pushing Dependencies
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: /tmp/dist.tar.gz
          retention-days: 1

  deploy:
    name: Deploy
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Packaging
        uses: actions/download-artifact@v2

      - name: Copy Artifacts
        run: |
          ls -l
          mkdir /tmp/tmp1
          tar xvzf ./dist/dist.tar.gz -C /tmp/tmp1
          aws s3 cp /tmp/tmp1 s3://stg-wallet.goldsikka.com/ --recursive --acl public-read